name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install nlohmann-json
        brew install googletest
        brew install curl
        brew install prometheus
        brew install prometheus-cpp
        brew install postgresql@14
        brew install libpqxx
        brew link postgresql@14 --force

    - name: Start PostgreSQL
      run: |
        brew services start postgresql@14
        sleep 3  # Wait for PostgreSQL to start

    - name: Setup PostgreSQL
      run: |
        # Drop database if exists and recreate
        dropdb cache_db || true
        createdb cache_db
        
        # Set environment variables for tests
        echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
        echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
        echo "POSTGRES_DB=cache_db" >> $GITHUB_ENV
        
        # Use default system user and trust authentication
        echo "POSTGRES_USER=$(whoami)" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=''" >> $GITHUB_ENV

        # Print configuration for debugging
        echo "Database configured with user: $(whoami)"
        psql -l

    - name: Start Prometheus
      run: |
        prometheus --config.file=./prometheus.yml &
        sleep 5

    - name: Build
      run: |
        make clean
        make all

    - name: Run Server Tests
      run: |
        ./server_tests

    - name: Run Database Tests
      run: |
        ./database_tests

    - name: Run Cache Tests
      run: |
        ./cache_tests

    - name: Run Integration Tests
      run: |
        # Start server in background
        ./server &
        SERVER_PID=$!
        sleep 5
        
        # Run some basic integration tests
        curl -X POST http://localhost:8080/api/cached \
          -H "Content-Type: application/json" \
          -d '{"key":"test","value":"value","ttl":300}'
        
        curl http://localhost:8080/api/cached/test
        
        curl -O -J "http://localhost:8080/api/export"
        
        # Cleanup
        kill $SERVER_PID || true

    - name: Stop Services
      if: always()
      run: |
        brew services stop postgresql@14
        pkill prometheus || true
