name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgtest-dev libcurl4-openssl-dev
        cd /usr/src/gtest
        sudo make
        sudo cp lib/libgtest*.a /usr/lib

    - name: Build and Test
      run: |
        make all
        ./server_tests
