name: C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install nlohmann-json
        brew install googletest
        brew install curl
        brew install prometheus
        brew install prometheus-cpp
    - name: Start Prometheus
      run: |
        prometheus --config.file=./prometheus.yml &
        sleep 5
    - name: Build and Test
      run: |
        make all
        ./server_tests
